# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingapp', '0002_auto_20160731_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=200)),
                ('projectStartData', models.DateField()),
                ('projectCostPerHr', models.FloatField(default=0.0)),
            ],
        ),
    ]
