# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountingapp', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectClient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountingapp.Client'),
        ),
    ]
