# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountingapp', '0004_project_projectclient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectStartData',
            new_name='projectStartDate',
        ),
    ]
