# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountingapp', '0005_auto_20160801_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workDescription', models.CharField(max_length=200)),
                ('hoursOfWork', models.FloatField(default=0.0)),
                ('dateOfWork', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingapp.Project')),
            ],
        ),
    ]
