# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingapp', '0007_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttimeentry',
            name='dateOfWork',
            field=models.DateField(auto_now_add=True),
        ),
    ]
