# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingapp', '0008_auto_20160802_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='clientCompany',
        ),
        migrations.AddField(
            model_name='client',
            name='clientCompanyInfo',
            field=models.CharField(default='testing', max_length=700),
            preserve_default=False,
        ),
    ]
